#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import sys
import os


TargetType = {
    'exe': 0,
    'dll': 1,
    'lib': 2
}


def printErr(msg, details = None):
    print('Error: ' + msg)
    if details != None:
        print('       ' + details)


def repFilename(file, ext):
    """
    @brief replace suffix name of the file
    @param file  filename
    @param ext   suffix name
    @return the filename that with the ext suffix name
    """
    ret = file.rfind('.')
    if ret == -1:
        return file + '.' + ext
    return file[:ret] + '.' + ext


def getFilenameNoext(file):
    """
    @brief get only file name exclude suffix name
    @param file  filename
    @return the filename that exclude suffix name
    """
    rlt = file
    ret = file.rfind('/')
    if ret != -1:
        rlt = file[ret + 1:]
    ret = file.rfind('.')
    if ret != -1:
        return rlt
    return rlt[:ret]


def getFilename(file):
    """
    @brief get only file name from full path
    @param file  full path
    @return the only filename
    """
    ret = file.rfind('/')
    if ret == -1:
        return file
    return file[ret + 1:]


def getFolder(file):
    """
    @brief get path of filename's parent folder
    @param file  filename
    @return the path
    """
    ret = file.rfind('/')
    if ret == -1:
        return '.'
    return file[0:ret]


def getLibLinkArg(libs):
    """
    @brief replace libs from list "[lib1, lib2...]" to string "-llib1 -llib2..."
    @param libs  libs list
    @return the string
    """
    rlt = ''
    for lib in libs:
        rlt += ' -l' + lib
    return rlt


def getFileType(filename):
    """
    @brief get language type of the file
    @param filename  filename
    @return 'CXX' or 'C'
    """
    name2type = { 'cxx': 'CXX', 'c': 'C', 'cpp': 'CXX' }
    for t in ['cxx', 'c', 'cpp']:
        if filename.lower().rfind(t) == len(filename) - len(t):
            if t in name2type:
                return name2type[t]
            else:
                return 'CXX'
    return 'CXX'


def setCompileArg(compiles, key, value):
    """
    @brief set compiles' key to value
    @param compiles  compile arguments list
    @param key       property key
    @param value     property value
    @return if key is exist return True, else False
    """
    if key in compiles:
        print("Change defaule compile setting " + key + ' ~')
        if 'LIBS' in key:
            compiles[key] += (value.split(' '))
        else:
            compiles[key] = value
        return True
    else:
        return False


def addProject(projects, name):
    """
    @brief add a project named name to projects list
    @param projects  projects list
    @param name      project name
    @return if operator is successful return True, else False
    """
    if not name.isalpha():
        return False
    print('Project ' + name + ' created...')
    projects[name] = {
        'compile': {},
        'src': [],
        'path': '.',
        'target': name,
        'type': TargetType['exe']
    }
    return True


def addProjectSrcs(projects, name, srcs):
    """
    @brief add some source files to project named name
    @param projects  projects list
    @param name      project name
    @param srcs      source files list
    @return None
    """
    for src in srcs:
        src = src.strip()
        if len(src) == 0:
            continue
        if not os.path.exists(src):
            return src
        projects[name]['src'].append(src)
        print('Add "' + src + '" to project ' + name + ' ...')


def setProjectAttr(projects, name, key, value):
    """
    @brief set property value with key of project named name
    @param projects  projects list
    @param name      project name
    @param srcs      source files list
    @return None
    """
    print('Change project ' + name + ' setting ' + key + ' ~')
    if key == 'path':
        projects[name]['path'] = value
    elif key == 'target':
        projects[name]['target'] = value
    elif key == 'type':
        if value in TargetType:
            projects[name]['type'] = TargetType[value]
        else:
            pass
    return 1, 2

def mkCompileConfig(compiles, out):
    print("Writing default compile arguments...")
    compiles['CLIBS'] = getLibLinkArg(compiles['CLIBS'])
    compiles['CXXLIBS'] = getLibLinkArg(compiles['CXXLIBS'])
    for x in compiles:
        out.write(x + ' = ' + compiles[x] + '\n')
    out.write('\n\n')
    print("Finished.")

def mkProjectConfig(compiles, project, out):
    # set this project's compile arguments
    compiler = {}
    for t in compiles:
        if t in project['compile']:
            if 'LIBS' in t:
                compiler[t] = getLibLinkArg(project['compile'][t])
            else:
                compiler[t] = project['compile'][t]
        else:
            compiler[t] = '${' + t + '}'
    CompileConfig = {
        'C': compiler['C'],
        'CFLAGS': compiler['CFLAGS'],
        'CLIBS': compiler['CLIBS'],
        'CXX': compiler['CXX'],
        'CXXFLAGS': compiler['CXXFLAGS'],
        'CXXLIBS': compiler['CXXLIBS'],
    }
    out.write(project['target'] + ' : ')
    files = ''
    ctype = 'CXX'
    oneline = True
    for src in project['src']:
        filename = getFilename(src)
        if getFileType(filename) == 'C':
            ctype = 'C'
        filename = repFilename(filename, 'o')
        if oneline:
            out.write(project['path'] + '/' + filename)
            oneline = False
        else:
            out.write(' \\\n  ' + project['path'] + '/' + filename)
        files += ' ' + project['path'] + '/' + filename
    out.write('\n\t' +
              CompileConfig['CXX'] + ' ' + CompileConfig[ctype + 'FLAGS'] +
              ' -o ' + project['path'] + '/' + project['target'] + ' ' + files +
              ' ' + CompileConfig[ctype + 'LIBS'] + '\n\n')
    rlt = {}
    for src in project['src']:
        filename = getFilename(src)
        targetName = getFilenameNoext(src)
        olddir = os.getcwd()
        pipe = os.popen(compiles[ctype] + ' ' + compiles[ctype + 'FLAGS'] +
                        ' -I' + getFolder(src) + ' -MM ' + src)
        text = pipe.read()
        ret = pipe.close()
        if ret != None:
            pass
        else:
            tmpstr = ''
            tmpstr += (project['path'] + '/' + text + '\t')
            tmpstr += (CompileConfig[ctype] + ' ' + CompileConfig[ctype + 'FLAGS'] +
                      ' -c -o ' + project['path'] + '/' + repFilename(filename, 'o ') + src + '\n\n')
            rlt[project['path'] + '/' + repFilename(filename, 'o ')] = (
                tmpstr, project['path'] + '/' + repFilename(filename, 'o '))
    return rlt


def mkProjectsConfig(compiles, projects, out):
    print("Writing project items...")
    out.write('all: ')
    oneline = True
    for x in projects:
        if oneline:
            out.write(projects[x]['target'])
            oneline = False
        else:
            out.write(' \\\n  ' + projects[x]['target'])
    out.write('\n\n')
    objFiles = {}
    for proname in projects:
        print("Writing project " + proname + "...")
        ret = mkProjectConfig(compiles, projects[proname], out)
        for x in ret:
            if not x in objFiles:
                objFiles[x] = ret[x]
    for x in objFiles:
        out.write(objFiles[x][0])
    out.write('.PHONY clean:\n\t')
    out.write('rm -rf ')
    for x in objFiles:
        out.write(objFiles[x][1] + ' ')
    out.write('\n')
    print("Finished.")

def mkMakefile(compiles, projects, out = sys.stdout):
    out.write('# This makefile is generated by FatWhale Build Tool\n')
    mkCompileConfig(compiles, out)
    mkProjectsConfig(compiles, projects, out)

def parseFile(mkfile, compiles, projects):
    try:
        file = open(mkfile, 'rb')
    except FileNotFoundError:
        print("Error! file " + mkfile + " is not exist!")
        return -1
    cnt = 0
    linenum = 0
    srcsTags = False
    nowName = None
    for line in file:
        linenum += 1
        line = line.decode('utf8').split('\n')[0].strip()
        if len(line) == 0 or line[0:1] == '#':
            continue
        cmd = line.split(' ')[0].split('{')[0].strip()
        parms = line[len(cmd):].strip()
        if not srcsTags:
            if cmd.lower() == 'project':
                for proname in parms.split():
                    if not addProject(projects, proname):
                        printErr('Project name could only contain a-z and A-Z.',
                                 mkfile + ':' + str(linenum) + ' Project name >' + proname + '<'
                                )
                        return -1
            elif cmd.lower() == 'compile':
                key = parms.split(' ')[0].strip().upper()
                value = parms[len(key):].strip()
                if not setCompileArg(compiles, key, value):
                    printErr('Project name could only contain a-z and A-Z.',
                             mkfile + ':' + str(linenum) + ' Project name >' + proname + '<'
                            )
                    return -1
            else:
                if cmd in projects:
                    if '{' in line:
                        srcsTags = True
                        nowName = cmd
                        ret = addProjectSrcs(
                            projects, cmd, line[line.find('{') + 1:].split()
                        )
                        if ret != None:
                            printErr('Source file is not exist!',
                                    mkfile + ':' + str(linenum) + ' Project name "' + ret + '"'
                                    )
                            return -1
                elif '.path' in cmd.lower() or '.type' in cmd.lower() or '.target' in cmd.lower():
                    name = cmd.split('.')
                    key = name[1].strip().lower()
                    name = name[0].strip()
                    if not name in projects:
                        pass
                    else:
                        setProjectAttr(projects, name, key, parms)
        elif srcsTags:
            cmd = nowName
            if '}' in line:
                srcsTags = False
                nowName = None
                line = line[0:line.find('}')]
            ret = addProjectSrcs(projects, nowName, line.split())
            if ret != None:
                printErr('Source file is not exist!',
                        mkfile + ':' + str(linenum) + ' Project name "' + ret + '"'
                        )
                return -1
    print("Parse successful!")
    return 0

if __name__ == '__main__':
    mkfile = 'SCutefile.mk'
    genfile = 'makefile'
    i = 1
    onames = []
    while i < len(sys.argv):
        arg = sys.argv[i]
        if arg == '-v' or arg == '--version':
            print(
"""
           oooOOOOOOOoooo
        ooo---------------ooo
       oOo-------------------ooo
     oOo------------------------ooo
   oo--------------------oOo------O
 O----------------------oo  o-------oo
O------------------------ooo---------O
O-------------------------------------oO                ooOo
oo--------------------------------------oo           ooooo-oO
 oOo--------------------------------------oo        oo-------O
   ooo----------------------------oo---------oo       O--------O
     ooo-------------------------ooo-----------oo     oo-o-----oO
        oo-------------------ooooo---------------o-oO    oo---oooooooo
          ooooooo---ooooooooooo----------------------oo  oo--ooo------Oo
              oooooO-ooo------oo----------------------oooo-------------ooooo
                   oo----------oo------------ooooooo----------------------oo
                    oo----------ooooooooo---oO-----oo----ooooooooooooooooOo
                     oO------------oo--oo---oO------oo-ooooo  ooooooooooo
                       Oo-------------oo----oo-------Ooo
                       Oooo-----------O-----oo----ooo
                       oo-ooo--------oo------O--ooo
                        oO--oOooo----oO------oOo
                          oooO   oooooOo-------o
                                       oooo----oO

        FatWhale Build Tool v0.2.0
            Surge Night

"""
            )
            exit(0)
        elif arg == '-?' or arg == '-h' or arg == '--help':
            print(
'Usage: fatwhale [options] [project_names...]\n' +
'Options:\n' +
'  -i filename, --input=filename     Use filename as input file instead of "SCutefile.mk"\n' +
'  -o filename, --output=filename    Use filename as output file instead of "makefile"\n' +
'  -?, -h, --help                    Print this message and exit\n' +
'  -v, --version                     Print the version number of fatwhale and exit\n' +
'\n' +
'Report bugs to <surgenight@hotmail.com>\n'
            )
            print(
"""
test this is
"""
            )
            exit(0)
        elif arg == '-i':
            try:
                mkfile = sys.argv[i + 1]
                i += 1
            except IndexError:
                printErr("No filename follows argument -i!")
                exit(-1)
        elif arg.find('--input') == 0:
            tar = arg.find('=')
            if tar != -1:
                genfile = arg[arg.find('='):]
            else:
                printErr("No filename follows argument --input!")
                exit(-1)
        elif arg == '-o':
            try:
                genfile = sys.argv[i + 1]
                i += 1
            except IndexError:
                printErr("No filename follows argument -o!")
                exit(-1)
        elif arg.find('--output') == 0:
            tar = arg.find('=')
            if tar != -1:
                genfile = arg[arg.find('='):]
            else:
                printErr("No filename follows argument --output!")
                exit(-1)
        else:
            onames.append(arg)
        i += 1
    compiles = {
        'C': 'gcc',
        'CFLAGS': '-Wall -Wextra',
        'CLIBS': [
        ],
        'CXX': 'g++',
        'CXXFLAGS': '-std=c++11 -Wall -Wextra',
        'CXXLIBS': [
        ]
    }
    projects = {}
    ret = parseFile(mkfile, compiles, projects)
    if ret != 0:
        exit(ret)
    if len(onames) != 0:
        oprojects = {}
        for name in onames:
            if name in projects:
                oprojects[name] = projects[name]
    else:
        oprojects = projects
    file = open(genfile, 'w')
    mkMakefile(compiles, oprojects, file)
    file.close()

